/**
 * BelleBook Error Types and Codes
 * All error types, codes, and mappings for the application
 */

export enum ErrorCategory {
  AUTHENTICATION = 'AUTHENTICATION',
  AUTHORIZATION = 'AUTHORIZATION',
  NETWORK = 'NETWORK',
  DATABASE = 'DATABASE',
  VALIDATION = 'VALIDATION',
  NOT_FOUND = 'NOT_FOUND',
  SERVER = 'SERVER',
  PAYMENT = 'PAYMENT',
  BOOKING = 'BOOKING',
  FILE_UPLOAD = 'FILE_UPLOAD',
  UNKNOWN = 'UNKNOWN',
}

export enum ErrorSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum ErrorCode {
  // Authentication (1000-1099)
  AUTH_INVALID_CREDENTIALS = 'AUTH_1001',
  AUTH_USER_NOT_FOUND = 'AUTH_1002',
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_1003',
  AUTH_WEAK_PASSWORD = 'AUTH_1004',
  AUTH_TOKEN_EXPIRED = 'AUTH_1005',
  AUTH_UNAUTHORIZED = 'AUTH_1006',
  AUTH_ACCOUNT_DISABLED = 'AUTH_1008',
  AUTH_TOO_MANY_REQUESTS = 'AUTH_1009',
  
  // Authorization (1100-1199)
  AUTHZ_INSUFFICIENT_PERMISSIONS = 'AUTHZ_1101',
  AUTHZ_FORBIDDEN_RESOURCE = 'AUTHZ_1102',
  
  // Network (2000-2099)
  NETWORK_OFFLINE = 'NET_2001',
  NETWORK_TIMEOUT = 'NET_2002',
  NETWORK_CONNECTION_FAILED = 'NET_2003',
  
  // Database (3000-3099)
  DB_CONNECTION_FAILED = 'DB_3001',
  DB_QUERY_FAILED = 'DB_3002',
  DB_DOCUMENT_NOT_FOUND = 'DB_3003',
  DB_PERMISSION_DENIED = 'DB_3004',
  DB_TRANSACTION_FAILED = 'DB_3006',
  
  // Validation (4000-4099)
  VALIDATION_REQUIRED_FIELD = 'VAL_4001',
  VALIDATION_INVALID_EMAIL = 'VAL_4002',
  VALIDATION_INVALID_PHONE = 'VAL_4003',
  VALIDATION_INVALID_DATE = 'VAL_4004',
  VALIDATION_INVALID_FORMAT = 'VAL_4007',
  
  // Not Found (5000-5099)
  NOT_FOUND_USER = 'NF_5001',
  NOT_FOUND_SERVICE = 'NF_5002',
  NOT_FOUND_BOOKING = 'NF_5003',
  NOT_FOUND_PAGE = 'NF_5006',
  
  // Server (6000-6099)
  SERVER_INTERNAL_ERROR = 'SRV_6001',
  SERVER_SERVICE_UNAVAILABLE = 'SRV_6002',
  SERVER_RATE_LIMIT = 'SRV_6004',
  
  // Payment (7000-7099)
  PAYMENT_DECLINED = 'PAY_7001',
  PAYMENT_PROCESSING_ERROR = 'PAY_7004',
  PAYMENT_CANCELLED = 'PAY_7006',
  
  // Booking (8000-8099)
  BOOKING_SLOT_UNAVAILABLE = 'BKG_8001',
  BOOKING_PAST_DATE = 'BKG_8003',
  BOOKING_CANCELLATION_FAILED = 'BKG_8004',
  
  // File Upload (9000-9099)
  FILE_TOO_LARGE = 'FILE_9001',
  FILE_INVALID_TYPE = 'FILE_9002',
  FILE_UPLOAD_FAILED = 'FILE_9003',
  
  UNKNOWN_ERROR = 'UNK_9999',
}

export interface ErrorDetails {
  code: ErrorCode;
  category: ErrorCategory;
  severity: ErrorSeverity;
  userMessage: string;
  technicalMessage: string;
  suggestedAction?: string;
}
